# Generated by ChatGPT - Form Builder models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable key, e.g. SIKKE, SERAMIK, MEZAR, FIGURIN, TERRACOTTA.', max_length=60, unique=True)),
                ('title', models.CharField(max_length=127)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=99)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Stable key used in JSON storage, e.g. 'coin.emperor' or 'measure.height'.", max_length=120, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('int', 'Integer'), ('decimal', 'Decimal'), ('date', 'Date'), ('bool', 'Boolean'), ('select', 'Select (List-backed)'), ('multiselect', 'Multi-select (List-backed)'), ('choice', 'Choice (static)'), ('file', 'File')], max_length=20)),
                ('bucket', models.CharField(choices=[('details', 'Details'), ('measurements', 'Measurements'), ('additives', 'Additives')], default='details', max_length=20)),
                ('section', models.CharField(blank=True, default='', help_text='UI section title', max_length=120)),
                ('help_text', models.CharField(blank=True, default='', max_length=255)),
                ('list_type', models.CharField(blank=True, default='', help_text='List source key (to be mapped later), e.g. COLOR, PERIOD, PRODUCTION_SITE.', max_length=60)),
                ('unit_group', models.CharField(blank=True, default='', help_text="Unit group, e.g. 'length' or 'weight'. Renderer can show unit selector.", max_length=30)),
                ('choices', models.JSONField(blank=True, help_text="For data_type='choice': [{'value':'0','label':'Az'}, ...].", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='MaterialGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='e.g. METAL, CERAMIC', max_length=60, unique=True)),
                ('title', models.CharField(max_length=127)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MaterialAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Altın, Bronz', max_length=127, unique=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='api.materialgroup')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArtifactFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False)),
                ('readonly', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=99)),
                ('visible_if', models.JSONField(blank=True, help_text='Optional rule object for conditional display. Leave null for always visible.', null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.fielddefinition')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='api.artifactform')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('form', 'field')},
            },
        ),
        migrations.CreateModel(
            name='MaterialFormMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=99)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.artifactform')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_maps', to='api.materialgroup')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('group', 'form')},
            },
        ),
    ]
