# Generated by Django 5.2.10 on 2026-01-18 20:02

from django.db import migrations, models


def forwards_findings(apps, schema_editor):
    LookupList = apps.get_model("api", "LookupList")
    LookupItem = apps.get_model("api", "LookupItem")
    MainCode = apps.get_model("core", "MainCode")

    lookup, _ = LookupList.objects.get_or_create(
        key="PRODUCTION_SITE",
        defaults={"title": "Üretim Yeri", "description": "MainCode Buluntu Yeri"},
    )

    items_by_value = {
        item.value: item
        for item in LookupItem.objects.filter(lookup=lookup)
    }

    to_update = []
    for mc in MainCode.objects.all():
        value = (mc.finding_place or "").strip()
        if not value:
            continue
        item = items_by_value.get(value)
        if not item:
            item = LookupItem.objects.create(
                lookup=lookup,
                value=value,
                label=value,
                order=99,
                is_active=True,
            )
            items_by_value[value] = item
        mc.finding_place_item = item
        to_update.append(mc)

    if to_update:
        MainCode.objects.bulk_update(to_update, ["finding_place_item"])


def backwards_findings(apps, schema_editor):
    MainCode = apps.get_model("core", "MainCode")
    to_update = []
    for mc in MainCode.objects.select_related("finding_place_item"):
        item = mc.finding_place_item
        mc.finding_place = item.label if item else ""
        to_update.append(mc)
    if to_update:
        MainCode.objects.bulk_update(to_update, ["finding_place"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_report_and_more"),
        ("api", "0003_lookup_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="maincode",
            name="finding_place_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.PROTECT,
                related_name="main_codes",
                to="api.lookupitem",
                verbose_name="Buluntu Yeri",
            ),
        ),
        migrations.RunPython(forwards_findings, backwards_findings),
        migrations.RemoveField(
            model_name="maincode",
            name="finding_place",
        ),
        migrations.RenameField(
            model_name="maincode",
            old_name="finding_place_item",
            new_name="finding_place",
        ),
        migrations.AlterField(
            model_name="maincode",
            name="finding_place",
            field=models.ForeignKey(
                on_delete=models.PROTECT,
                related_name="main_codes",
                to="api.lookupitem",
                verbose_name="Buluntu Yeri",
            ),
        ),
    ]
