# Generated by Django 5.2.10 on 2026-01-18 20:02

from django.db import migrations, models


def forwards_report_findings(apps, schema_editor):
    LookupList = apps.get_model("api", "LookupList")
    LookupItem = apps.get_model("api", "LookupItem")
    Report = apps.get_model("core", "Report")

    lookup, _ = LookupList.objects.get_or_create(
        key="FINDING_PLACE",
        defaults={"title": "Buluntu Yeri", "description": "Report Buluntu Yeri"},
    )

    items_by_value = {
        item.value: item
        for item in LookupItem.objects.filter(lookup=lookup)
    }

    to_update = []
    for report in Report.objects.all():
        value = (report.finding_place or "").strip()
        if not value:
            continue
        item = items_by_value.get(value)
        if not item:
            item = LookupItem.objects.create(
                lookup=lookup,
                value=value,
                label=value,
                order=99,
                is_active=True,
            )
            items_by_value[value] = item
        report.finding_place_item = item
        to_update.append(report)

    if to_update:
        Report.objects.bulk_update(to_update, ["finding_place_item"])


def backwards_report_findings(apps, schema_editor):
    Report = apps.get_model("core", "Report")
    to_update = []
    for report in Report.objects.select_related("finding_place_item"):
        item = report.finding_place_item
        report.finding_place = item.label if item else ""
        to_update.append(report)
    if to_update:
        Report.objects.bulk_update(to_update, ["finding_place"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_maincode_finding_place_fk"),
        ("api", "0003_lookup_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="finding_place_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.PROTECT,
                related_name="reports",
                to="api.lookupitem",
                verbose_name="Buluntu Yeri",
            ),
        ),
        migrations.RunPython(forwards_report_findings, backwards_report_findings),
        migrations.RemoveField(
            model_name="report",
            name="finding_place",
        ),
        migrations.RenameField(
            model_name="report",
            old_name="finding_place_item",
            new_name="finding_place",
        ),
        migrations.AlterField(
            model_name="report",
            name="finding_place",
            field=models.ForeignKey(
                on_delete=models.PROTECT,
                related_name="reports",
                to="api.lookupitem",
                verbose_name="Buluntu Yeri",
            ),
        ),
    ]
